.github/pull_request_template.md
CONTRIBUTING.md

Adicionando o Guia de Contribuição e ajustando o template de PR
N/A
| N/A  | N/A |

Feature templates issues

---

CONTRIBUTING.md

Atualização do Guia de Contribuição
Closes Issue #4 
| N/A  | N/A |

doc(contribuicao): Update guia de contribuicao

---

CONTRIBUTING.md

Realização de pequenos ajustes em relação a padronização de commits e branchs
N/A
| N/A  | N/A |

feat(comtibuicao): Update do Guia de Contribuicao

---

CONTRIBUTING.md

Realização de pequenos ajustes em relação a padronização de commits e branchs
Closes #4
| N/A  | N/A |

feat(contribuicao): Update do Guia de Contribuicao

---

.github/pull_request_template.md

Correção da URL do Guia do Contribuidor no template de PR
Resolved #8 
| N/A  | N/A |

fix(templates): correcao url do guia do contribuidor - Resolved #8

---

README.md

Documentação do Roadmap
N/A
| N/A  | N/A |

doc(roadmap): doc roadmap

---

CONTRIBUTING.md

Adicionando a documentação de como criar um PR ao Guia do Contribuidor
| N/A  | N/A |

docs(guia): Add como criar um pull request ao guia

---

.github/workflows/blank.yml

Automação de validação de um PR
Não está relacionado a nenhuma Issue
| N/A  | N/A |

feat(action): Create blank.yml

---

.github/pr-title-styles.json

Automação para validação de PR
N/A
| N/A  | N/A |

feat(action): automacao para validacao de pr

---

.github/workflows/main.yml
TESTING_PR.md

feat: teste pr 2

---

.github/workflows/main.yml
TESTING_PR.md

Teste de validação de PR número 3
N/A 
| N/A  | N/A |

feat(teste): Teste PR 3

---

.github/workflows/main.yml
TESTING_PR.md

Teste de validação PR 4
N/A
| N/A  | N/A |

feat: teste pr 4

---

.github/workflows/main.yml

Teste de validação de PR e auto merge
N/A
| N/A  | N/A |

fix: correcao do action

---

.github/workflows/main.yml
TESTING_PR.md

Validação de PR 5
N/A
| N/A  | N/A |

feat: teste pr 5

---

.github/workflows/main.yml
TESTING_PR.md

Validação de PR 8 e auto merge.
N/A
| N/A  | N/A |

feat: teste validacao de PR 8

---

.github/workflows/main.yml
TESTING_PR.md

feat: teste pr 9

---

.github/workflows/main.yml
TESTING_PR.md

Teste PR validation 10
N/A
| N/A  | N/A |

feat: teste 10 pr validation

---

.github/workflows/main.yml
TESTING_PR.md

Teste PR 10
N/A
| N/A  | N/A |

feat: teste pr 10

---

.github/workflows/main.yml

Ajustando Steps da Action
N/A
| N/A  | N/A |

feat: ajuste action steps

---

TESTING_PR.md

Validacao PR 12
N/A
| N/A  | N/A |

feat(validation): validacao pr 12

---

TESTING_PR.md

doc: teste pr 13

---

.github/pr-title-checker-config.json
.github/workflows/main.yml

Teste com o Step de validação de PR
N/A
| N/A  | N/A |

feat: ajuste do step de validacao de pr

---

.github/workflows/main.yml
TESTING_PR.md

Validacao PR 14
N/A
| N/A  | N/A |

feature: validacao pr 14

---

.github/workflows/main.yml
TESTING_PR.md

feature: Testing 15

---

.github/pr-title-checker-config.json
TESTING_PR.md

feature: Testing 16

---

.github/pr-title-checker-config.json
TESTING_PR.md

Teste pr 19
N/A
| N/A  | N/A |

feat: teste pr 19

---

TESTING_PR.md

Teste PR 20
N/A
| N/A  | N/A |

docs(v2): teste validate pr 20

---

.github/pr-title-checker-config.json

feat(v09): format json title checker

---

.github/pr-title-checker-config.json
TESTING_PR.md

Testing 21 PR
N/A
| N/A  | N/A |

feat(test): Testing 21 PR

---

.github/pr-title-checker-config.json
TESTING_PR.md

Testing PR 22
N/A
| N/A  | N/A |

feat(validation): Testing PR 22

---

.github/pr-title-checker-config.json
TESTING_PR.md

Validação de Titulo e automerge - PR 23
N/A
| N/A  | N/A |

feat(pr): validação de titulo e automerge PR 23

---

.github/pr-title-checker-config.json
TESTING_PR.md

Testing PR 25
N/A
| N/A  | N/A |

feat(pr): Testing PR 25

---

TESTING_PR.md

feat(pr): Testing PR 26

---

TESTING_PR.md

Teste PR 28 - Fora do padrão
N/A
| N/A  | N/A |

feat(teste): PR 28 Validacao

---

TESTING_PR.md

feat: passando um titulo fora do padrao

---

TESTING_PR.md

fix(validate): fora padrao

---

README.md

Adicionando bloco de contributers na documentação
N/A
| N/A  | N/A |

docs(contributors): Update Readme

---

.github/pull_request_template.md
CONTRIBUTING.md
contribution_project.md

Update Template PR
N/A
| N/A  | N/A |

docs(pr): Update Template PR

---

.github/pull_request_template.md
contribution_project.md

Update Teste PR
N/A
| N/A  | N/A |

feat(pr): teste pr

---

CONTRIBUTING.md

Adicionando intruções para praticar a contribuiçã com o projeto
| N/A  | N/A |

docs(contruibuicao): Update Guia do contribuidor

---

README.md

Correção do link de contribuição na documentação
| N/A  | N/A |

docs(fix): correcao do link de contribuicao

---

contribution_project.md

Ajuste do arquivo contribution_project.md
| N/A  | N/A |

fix(moura): ajuste de texto teste

---

README.md

Correção da exibição do contribuidores
| N/A  | N/A |

fix(moura): correcao da exibicao dos contribuidores

---

LICENSE

Add license file
| N/A  | N/A |

docs(license): add license file

---

.github/ISSUE_TEMPLATE/feature_request.md
LICENSE
README.md
contribution_project.md

Add campo ao template issue feature request
| N/A  | N/A |

 feat(issue): update template issue

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Ajuste templates Issue
Closes #63 
Ajustando templates Issues
| N/A  | N/A |

feat(template): ajuste templates issue

---

contribution_project.md

feat(teste): contrib 1

---

contribution_project.md

feat(contrib): contribution1

---

contribution_project.md

docs(contrib): contrib 2

---

contribution_project.md

feat(contrib): contrib 2

---

contribution_project.md

feat(contrib): contribuicao3

---

CONTRIBUTING.md
README.md

Atualizacao do guia do contribuidor
| N/A  | N/A |

docs(contribution): Atualizacao do guia do contribuidor

---

README.md

Update roadmap readme
| N/A  | N/A |

docs(readme): Update roadmap readme

---

.github/workflows/main.yml

Add validacao de arquivos modificados
| N/A  | N/A |

feat(actions): add validacao de arquivos modificados

---

.github/workflows/main.yml
contribution_project.md

Action validation
| N/A  | N/A |

feat(validation): action validation

---

.github/workflows/main.yml
contribution_project.md

contributions 5
| N/A  | N/A |

feat(contribution): contributions 5

---

.github/workflows/main.yml
contribution_project.md

Add contribution number one
| N/A  | N/A |

docs(contrib): Add contribution number one

---

.github/workflows/main.yml
contribution_project.md

Contribution number two
| N/A  | N/A |

docs(contribution): Contribution number two

---

.github/workflows/main.yml
contribution_project.md

Contribution number 3
| N/A  | N/A |

docs(contrib): contribution number 3

---

.github/workflows/main.yml
contribution_project.md

Contribution number 4
| N/A  | N/A |

docs(contribution): Contribution number 4

---

.github/workflows/main.yml
contribution_project.md

docs(contrib): contribution 5

---

contribution_project.md

docs(contrib): contribution 1

---

.github/workflows/main.yml

fix(actions): Ajuste actions

---

.github/workflows/main.yml
contribution_project.md

Contribution 2 - Validação da action - Checando arquivo modificado
Closes #70 
Adicionando Step de validação de arquivo modificado
| N/A  | N/A |

docs(contribution): contribution 2

---

contribution_project.md

docs(contrib): contrib 1

---

.github/workflows/main.yml

feat(action): ajuste actions

---

contribution_project.md

Validation action
Closes #70 
Adicionando step para validar arquivos modificados
| N/A  | N/A |

docs(contrib): Validation action

---

.github/workflows/main.yml
README.md

Adicionando referências para utilização de variaveis
| N/A  | N/A |

docs(readme): add ref variaveis

---

.github/workflows/main.yml
README.md

Update Referências no readme
| N/A  | N/A |

docs(readme): update readme

---

README.md

Adicionando referência do title pr checker no readme
| N/A  | N/A |

docs(readme): Update readme add ref

---

contribution_project.md

feat(contribution): Contribution 1

---

.github/workflows/main.yml

file not allowed
| N/A  | N/A |

feat(action): add label file not allowed

---

contribution_project.md

feat(contrib): contribution 2

---

SECURITY.md

Add modelo inicial SECURITY.md
| N/A  | N/A |

docs(security): add securitymd

---

.github/config.yml
CONTRIBUTING.md
SECURITY.md

Adicionando um termo de segurança iniciar e como reportar vulnerabilidades
Ajustando o Guia de Contribuição, add steps a respeito do fork do projeto
Adicionando um arquivo de configuação para desabilitar o report de issues em branco
N/A
| N/A  | N/A |

docs(securit): add files security

---

.github/ISSUE_TEMPLATE/config.yml

docs(configs): ajustando configs issues templates

---

.github/ISSUE_TEMPLATE/config.yml

Adicionarndo arquivo de configuração para redirecionamento ao forum durante a abertura de issues
| N/A  | N/A |

docs(config): add config para redirecinar ao forum

---

README.md

docs(readme): correcao readme
